### ISSUE TITLE
Support `selector` for rules

### ISSUE THREAD

**Issue by hudochenkov** [hudochenkov/stylelint-declaration-block-order#2]
Config:

``` js
{
    type: 'rule',
    selector: '/^&:\w/'
}
```

`selector` is RegEx for selector matching.

It will match:

``` scss
a {
    &:hover {
        color: blue;
    }
    &:focus {
        color: red;
    }
}
```

Won't match:

``` scss
a {
    &::before {
        content: "b";
    }
    &::after {
        content: "a";
    }
}
```

Proposed https://github.com/stylelint/stylelint/issues/1500#issuecomment-230105435
